"""EaStore 协议与工厂(镜像 gold-bot packages/persistence/src/index.ts 的 EaStore 接口)。"""

from __future__ import annotations

from typing import Protocol

from backend.persistence.records import EaRecord, PersistenceStatus, StoredCommand

persistence_status = PersistenceStatus()


class EaStore(Protocol):
    """交易引擎持久层契约(与 TS EaStore 一一对应)。

    SQLite 版与内存版必须语义一致;由共享测试套件 tests/unit/persistence/test_store_suite.py 保证。
    """

    # ---- EA 生命周期快照
    async def save_registration(self, payload: EaRecord) -> None: ...
    async def get_registration(self, account_id: str) -> EaRecord | None: ...
    async def save_heartbeat(self, payload: EaRecord) -> None: ...
    async def get_heartbeat(self, account_id: str) -> EaRecord | None: ...
    async def save_tick(self, payload: EaRecord) -> None: ...
    async def get_latest_tick(self, account_id: str, symbol: str) -> EaRecord | None: ...
    async def save_bars(self, payload: EaRecord) -> None: ...
    async def get_bars(self, account_id: str, symbol: str, timeframe: str) -> list[EaRecord]: ...
    async def claim_bar_close_event(
        self, account_id: str, symbol: str, timeframe: str, bar_time: str
    ) -> bool: ...
    async def save_positions(self, payload: EaRecord) -> None: ...
    async def get_positions(self, account_id: str, symbol: str | None = None) -> list[EaRecord]: ...

    # ---- 持仓状态
    async def save_position_state(self, account_id: str, symbol: str, state: EaRecord) -> None: ...
    async def load_position_states(self, account_id: str, symbol: str) -> list[EaRecord]: ...
    async def delete_stale_position_states(self, account_id: str, symbol: str, active_tickets: list[int]) -> None: ...

    # ---- 订单回报
    async def save_order_result(self, payload: EaRecord) -> None: ...
    async def get_order_results(self, account_id: str) -> list[EaRecord]: ...

    # ---- 命令生命周期
    async def enqueue_command(self, account_id: str, command: EaRecord) -> None: ...
    async def save_command_candidate(self, account_id: str, candidate: EaRecord) -> StoredCommand: ...
    async def promote_command(self, command_id: str) -> None: ...
    async def demote_command_to_shadow_only(self, command_id: str) -> None: ...
    async def get_command(self, command_id: str) -> StoredCommand | None: ...
    async def list_commands(self, account_id: str) -> list[StoredCommand]: ...
    async def has_active_ai_approve_pending(self, account_id: str, symbol: str, side: str, now_iso: str) -> bool: ...
    async def get_runtime_mode(self, account_id: str) -> str: ...
    async def set_runtime_mode(self, account_id: str, mode: str) -> None: ...
    async def reconcile_command_result(
        self,
        account_id: str,
        command_id: str,
        result: str,
        ticket: int | None = None,
        error_text: str = "",
        created_at: str | None = None,
    ) -> bool: ...
    async def poll_commands(self, account_id: str) -> list[EaRecord]: ...

    # ---- 影子校验
    async def record_shadow_comparison(self, payload: EaRecord) -> None: ...
    async def list_shadow_comparisons(self, filter_: EaRecord | None = None) -> list[EaRecord]: ...
    async def summarize_shadow_comparisons(self, filter_: EaRecord | None = None) -> EaRecord: ...
    async def save_shadow_snapshot(self, payload: EaRecord) -> None: ...
    async def get_latest_shadow_snapshot(self, account_id: str, symbol: str, source: str) -> EaRecord | None: ...

    # ---- 决策时间线
    async def record_decision_event(self, payload: EaRecord) -> None: ...
    async def list_decision_events(self, filter_: EaRecord) -> list[EaRecord]: ...

    # ---- 候选信号(仲裁)
    async def save_pending_signal(self, payload: EaRecord) -> None: ...
    async def get_pending_signals(self, account_id: str, symbol: str) -> list[EaRecord]: ...
    async def get_pending_signal_by_id(self, account_id: str, symbol: str, id: int) -> EaRecord | None: ...
    async def update_pending_signal_arbitration(self, id: int, result: str, reason: str) -> bool: ...
    async def expire_pending_signals(self, now_iso: str) -> int: ...

    # ---- AI 结果
    async def save_ai_result(self, account_id: str, symbol: str, payload: EaRecord) -> None: ...
    async def get_ai_results(self, account_id: str) -> list[EaRecord]: ...

    # ---- Token
    async def save_api_token(self, payload: EaRecord) -> None: ...
    async def list_api_tokens(self) -> list[EaRecord]: ...
    async def delete_api_token(self, token: str) -> bool: ...

    # ---- 账户/品种
    async def list_account_ids(self) -> list[str]: ...
    async def list_symbols(self, account_id: str) -> list[str]: ...
    async def list_ai_symbols(self, account_id: str) -> list[str]: ...

    # ---- 已平仓/日权益
    async def save_closed_trade(self, payload: EaRecord) -> None: ...
    async def get_closed_trade_stats(self, account_id: str) -> list[EaRecord]: ...
    async def get_daily_start_equity(self, account_id: str, utc_date: str) -> float | None: ...
    async def save_daily_start_equity(self, account_id: str, utc_date: str, equity: float) -> None: ...

    async def close(self) -> None: ...


def create_in_memory_store() -> EaStore:
    from backend.persistence.inmemory import InMemoryEaStore

    return InMemoryEaStore()


def create_sqlite_store(path: str) -> EaStore:
    """创建 SQLite store;初始化时先执行全部未应用 migration(与 TS 一致)。"""
    from backend.persistence.migrate import run_migrations_sync
    from backend.persistence.sqlite_store import SqliteEaStore

    run_migrations_sync(db_path=path)
    return SqliteEaStore(path)
